# values/backend-values.yaml
image:
  repository: 138537744457.dkr.ecr.eu-west-1.amazonaws.com/warehouse-backend
  tag: a9aff83db472ffaf78f43e3d94aa25a6ef8fea2a
  pullPolicy: Always

imagePullSecrets: []

replicaCount: 2