# values/backend-values.yaml
image:
  repository: 138537744457.dkr.ecr.eu-west-1.amazonaws.com/warehouse-backend
  tag: ffde12c417d93cf98b5549bd9f1e40adf859805f
  pullPolicy: Always

imagePullSecrets: []

replicaCount: 2