# apps/secrets/mysql-external-secret.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: warehouse
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef:
        key: warehouse/mysql
        property: root_password
    - secretKey: password
      remoteRef:
        key: warehouse/mysql
        property: password
