image:
  repository: 138537744457.dkr.ecr.eu-west-1.amazonaws.com/warehouse-ai-tagging
  tag: 6d1818ada93491efe65f6b5d58bea7d2a57be13e
  pullPolicy: Always
imagePullSecrets: []
replicaCount: 1
resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::138537744457:role/warehouse-cluster-ai-tagging-bedrock