image:
  repository: 138537744457.dkr.ecr.eu-west-1.amazonaws.com/warehouse-auth-service
  tag: 0a917d0f149a0098fe66607d39a19664a5225b98
  pullPolicy: Always
imagePullSecrets: []
replicaCount: 2
resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi