# values/backend-values.yaml
image:
  repository: 138537744457.dkr.ecr.eu-west-1.amazonaws.com/warehouse-backend
  tag: 5f677fc1b5f03d74eeec98af5a930a2d655ab295
  pullPolicy: Always

imagePullSecrets: []

replicaCount: 2